version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "github"
            - "Docker Hub"

commands:
  setup:
    steps:
      - run:
          name: Prepare for multi arch build (setup qemu)
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-arm-static --version
            qemu-aarch64-static --version
            update-binfmts --version 
      - run:
          name: Create multi arch docker image builder
          command: |
            docker buildx create --name multi-arch-builder
            docker buildx use multi-arch-builder
            docker buildx inspect --bootstrap
      - checkout

jobs:
  build:
    machine: true
    steps:
      - setup
      - run:
          name: Build docker image
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            TAG_NAME="${DOCKER_USER}/asciidoctor"
            if [ "${CIRCLE_TAG}" != "" ]; then
              TAG_NAME+=":${CIRCLE_TAG}"
            fi
            docker buildx build \
              --platform linux/amd64,linux/arm/v7,linux/arm64 \
              --tag ${TAG_NAME} \
              --build-arg CIRCLE_TAG=${CIRCLE_TAG:-latest} \
              --build-arg ASCIIDOCTOR_BASE_TAG=${CIRCLE_TAG:-latest} \
              --build-arg BUILDKIT_MULTI_PLATFORM=1 \
              --no-cache \
              --progress=plain \
              --push .
