version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "github"
            - "Docker Hub"
      - test-amd64:
          requires:
            - build
          context:
            - "github"
            - "Docker Hub"
      - test-arm64:
          requires:
            - build
          context:
            - "github"
            - "Docker Hub"
      - example-build:
          requires:
            - test-amd64
            - test-arm64
          context:
            - "github"
            - "Docker Hub"
      - example-deploy:
          requires:
            - example-build
          context:
            - "github"
          filters:
            branches:
              only: main
commands:
  setup-multi-arch-docker:
    steps:
      - run:
          name: Prepare for multi arch build (setup qemu)
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-arm-static --version
            qemu-aarch64-static --version
            update-binfmts --version 
      - run:
          name: Create multi arch docker image builder
          command: |
            docker buildx create --name multi-arch-builder
            docker buildx use multi-arch-builder
            docker buildx inspect --bootstrap

jobs:

  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - setup-multi-arch-docker
      - checkout
      - run:
          name: Build docker image
          no_output_timeout: 1h
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            TAG_NAME="${DOCKER_USER}/asciidoctor"
            TAG="--tag ${TAG_NAME}:latest"
            ASCIIDOCTOR_BASE_TAG=${CIRCLE_TAG:-latest}
            if [ "${CIRCLE_TAG}" != "" ]; then
              TAG="--tag ${TAG_NAME}:${CIRCLE_TAG} --tag ${TAG_NAME}:${CIRCLE_TAG%%.*} --tag ${TAG_NAME}:${CIRCLE_TAG%.*} --tag ${TAG_NAME}:stable"
              ASCIIDOCTOR_BASE_TAG=${CIRCLE_TAG%.*}
            fi
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              ${TAG} \
              --build-arg CIRCLE_TAG=${CIRCLE_TAG:-latest} \
              --build-arg ASCIIDOCTOR_BASE_TAG=${ASCIIDOCTOR_BASE_TAG} \
              --build-arg CONTAINER_INFORMATION="${TAG_NAME}:${CIRCLE_TAG:-latest} (${CIRCLE_SHA1})" \
              --build-arg BUILDKIT_MULTI_PLATFORM=1 \
              --no-cache \
              --progress=plain \
              --push .

  test-amd64:
    docker:
      - image: ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}
    resource_class: medium
    steps:
      - run:
          name: Test docker image (linux/amd64)
          no_output_timeout: 1h
          command: |
            echo "${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}"
            asciidoctor -B "/documents" --version
            inliner --help

  test-arm64:
    docker:
      - image: ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}
    resource_class: arm.medium
    steps:
      - run:
          name: Test docker image (linux/arm64)
          no_output_timeout: 1h
          command: |
            echo "${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}"
            asciidoctor -B "/documents" --version
            inliner --help

  example-build:
    docker:
      - image: ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}
    working_directory: /project
    steps:
      - run:
          name: Create project directory
          command: |
            mkdir -p "${CIRCLE_WORKING_DIRECTORY}"
      - checkout
      - run:
          name: Delete and create dist directory
          command: |
            rm -rf /dist/*
            mkdir -p /dist/css
      - run:
          name: Asciidoctor version
          command: |
            echo "${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}"
            asciidoctor -B "${CIRCLE_WORKING_DIRECTORY}/src/doc" --version
      - run:
          name: Generate HTML
          no_output_timeout: 1h
          command: |
            asciidoctor \
              --trace \
              --verbose \
              -b html5 \
              -D /dist \
              -B "${CIRCLE_WORKING_DIRECTORY}/src/doc" \
              -r asciidoctor-diagram \
              -r asciidoctor-mathematical \
              -r /usr/local/asciidoctor-extensions/lib/glob-include-processor.rb \
              -a projectVersion="${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}" \
              -a revisionDate="${REVISION_DATE}" \
              "${CIRCLE_WORKING_DIRECTORY}/src/doc/asciidoctor-diagram_overview.adoc"
      - run:
          name: Inline HTML
          no_output_timeout: 1h
          command: |
            inliner \
              --nocompress \
              --preserve-comments \
              --inlinemin \
              --videos \
              /dist/asciidoctor-diagram_overview.html \
              2>/dev/null \
              1> /dist/asciidoctor-diagram_overview_inlined.html
      - run:
          name: Generate PDF
          no_output_timeout: 1h
          command: |
            asciidoctor-pdf \
              --trace \
              --verbose \
              -D /dist \
              -B "${CIRCLE_WORKING_DIRECTORY}/src/doc" \
              -r asciidoctor-diagram \
              -r asciidoctor-mathematical \
              -r /usr/local/asciidoctor-extensions/lib/glob-include-processor.rb \
              -a projectVersion="${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}" \
              -a revisionDate="${REVISION_DATE}" \
              "${CIRCLE_WORKING_DIRECTORY}/src/doc/asciidoctor-diagram_overview.adoc"
      - run:
          name: Generate index.html
          no_output_timeout: 1h
          command: |
            asciidoctor \
              --trace \
              --verbose \
              -b html5 \
              -D /dist \
              -B "${CIRCLE_WORKING_DIRECTORY}/src/doc" \
              -r asciidoctor-diagram \
              -r asciidoctor-mathematical \
              -r /usr/local/asciidoctor-extensions/lib/glob-include-processor.rb \
              -a projectVersion="${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}" \
              -a revisionDate="${REVISION_DATE}" \
              "${CIRCLE_WORKING_DIRECTORY}/src/doc/index.adoc"
      - persist_to_workspace:
          root: /dist
          paths: 
            - .

  example-deploy:
    docker:
      - image: node:lts
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: /dist
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@5.0.0
            git config user.email "circle-ci@users.noreply.github.com"
            git config user.name "circle-ci"
      - add_ssh_keys:
          fingerprints:
            - "44:0d:4e:92:0b:49:7d:99:c0:ad:c3:6b:f4:d4:db:67"
      - run:
          name: Deploy example to gh-pages branch
          command: |
            gh-pages \
            --message "[skip ci] Updated by ${CIRCLE_BUILD_URL}" \
            -d /dist
          environment:
            CACHE_DIR: /tmp
            NODE_DEBUG: gh-pages
