version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          context:
            - "github"
            - "Docker Hub"
      - example-build:
          requires:
            - build
          context:
            - "github"
            - "Docker Hub"
      - example-deploy:
          requires:
            - build
            - example-build
          context:
            - "github"
          filters:
            branches:
              only: main
commands:
  setup:
    steps:
      - run:
          name: Prepare for multi arch build (setup qemu)
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-arm-static --version
            qemu-aarch64-static --version
            update-binfmts --version 
      - run:
          name: Create multi arch docker image builder
          command: |
            docker buildx create --name multi-arch-builder
            docker buildx use multi-arch-builder
            docker buildx inspect --bootstrap

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - setup
      - checkout
      - run:
          name: Build docker image
          no_output_timeout: 1h
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            TAG_NAME="${DOCKER_USER}/asciidoctor"
            if [ "${CIRCLE_TAG}" != "" ]; then
              TAG_NAME+=":${CIRCLE_TAG}"
            else
              TAG_NAME+=":latest"
            fi
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag ${TAG_NAME} \
              --build-arg CIRCLE_TAG=${CIRCLE_TAG:-latest} \
              --build-arg ASCIIDOCTOR_BASE_TAG=${CIRCLE_TAG:-latest} \
              --build-arg BUILDKIT_MULTI_PLATFORM=1 \
              --no-cache \
              --progress=plain \
              --push .
  example-build:
    machine:
      image: ubuntu-2204:2023.02.1
    steps:
      - checkout
      - run:
          name: Delete and create dist directory
          command: |
            rm -rf .examples
            mkdir -p .examples/dist/css
            ls -al .
      - run:
          name: Pull docker image
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker pull ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest}
      - run:
          name: Generate HTML
          no_output_timeout: 1h
          command: |
            docker run --rm \
              -v $(pwd)/src/doc:/documents/ \
              -v $(pwd)/.examples/dist:/dist \
              ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest} \
                asciidoctor \
                  -b html5 \
                  -D "/dist" \
                  -r asciidoctor-diagram \
                  -r asciidoctor-mathematical \
                  -r /usr/local/asciidoctor-extensions/lib/glob-include-processor.rb \
                  -a projectVersion="${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}" \
                  -a revisionDate="${REVISION_DATE}" \
                  /documents/asciidoctor-diagram_overview.adoc
      - run:
          name: Inline HTML
          no_output_timeout: 1h
          command: |
            docker run --rm \
              -v $(pwd)/.examples/dist:/dist \
              -it \
              ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest} \
                inliner \
                  --nocompress \
                  --preserve-comments \
                  --inlinemin \
                  --videos \
                  /dist/asciidoctor-diagram_overview.html \
                  2>/dev/null \
                  1> .examples/dist/asciidoctor-diagram_overview_inlined.html
      - run:
          name: Generate PDF
          no_output_timeout: 1h
          command: |
            docker run --rm \
              -v $(pwd)/src/doc:/documents/ \
              -v $(pwd)/.examples/dist:/dist \
              ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest} \
                asciidoctor-pdf \
                  -D "/dist" \
                  -r asciidoctor-diagram \
                  -r asciidoctor-mathematical \
                  -r /usr/local/asciidoctor-extensions/lib/glob-include-processor.rb \
                  -a projectVersion="${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}" \
                  -a revisionDate="${REVISION_DATE}" \
                  /documents/asciidoctor-diagram_overview.adoc
      - run:
          name: Generate index.html
          no_output_timeout: 1h
          command: |
            docker run --rm \
              -v $(pwd)/src/doc:/documents/ \
              -v $(pwd)/.examples/dist:/dist \
              ${DOCKER_USER}/asciidoctor:${CIRCLE_TAG:-latest} \
                asciidoctor \
                  -b html5 \
                  -D "/dist" \
                  -r asciidoctor-diagram \
                  -r asciidoctor-mathematical \
                  -r /usr/local/asciidoctor-extensions/lib/glob-include-processor.rb \
                  -a projectVersion="${CIRCLE_TAG:-${CIRCLE_SHA1:0:8}}" \
                  -a revisionDate="${REVISION_DATE}" \
                  /documents/index.adoc
      - persist_to_workspace:
          root: .examples
          paths: dist
  example-deploy:
    docker:
      - image: node:lts
    steps:
      - checkout
      - attach_workspace:
          at: .examples
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@5.0.0
            git config user.email "circle-ci@users.noreply.github.com"
            git config user.name "circle-ci"
      - add_ssh_keys:
          fingerprints:
            - "44:0d:4e:92:0b:49:7d:99:c0:ad:c3:6b:f4:d4:db:67"
      - run:
          name: Deploy example to gh-pages branch
          command: |
            gh-pages \
            --message "[skip ci] Updated by ${CIRCLE_BUILD_URL}" \
            -d .examples/dist
          environment:
            CACHE_DIR: /tmp
            NODE_DEBUG: gh-pages