// Adds configuration for easier preview.
include::../_preview_config.adoc[]

[[section-blockdiag-chapter]]
== Blockdiag

[quote, Takeshi KOMIYA, http://blockdiag.com/en/index.html]
____
_blockdiag_ and its family generate diagram images from simple text files.
____

_blockdiag_ supports many types of diagrams like

* activity diagram (w/ <<section-actdiag>>) and
* block diagram (w/ <<section-blockdiag>>),
* logical network diagram (w/ <<section-nwdiag>>).
* sequence diagram (w/ <<section-seqdiag>>),

All these tools layouts diagram elements automatically and generates beautiful diagram images from simple text format (similar to graphviz’s DOT format).

[[section-actdiag]]
=== actdiag

[quote, Takeshi KOMIYA, http://blockdiag.com/en/actdiag/index.html]
____
_actdiag_ is a simple activity-diagram image generator and generates activity-diagram images from .diag files (similar to graphviz’s DOT files).
____

==== Internal diagram source

[actdiag, "actdiag-internal-example-diagram", svg]
----
actdiag {
  write -> convert -> image

  lane user {
     label = "User"
     write [label = "Writing reST"];
     image [label = "Get diagram IMAGE"];
  }
  lane actdiag {
     convert [label = "Convert reST to Image"];
  }
}
----

==== External diagram source file

actdiag::{imagesdir}/asciidoctor-diagrams_overview/uml/blockdiag_actdiag.diag[format="svg"]

[[section-blockdiag]]
=== blockdiag

[quote, Takeshi KOMIYA, http://blockdiag.com/en/blockdiag/index.html]
____
_blockdiag_ generates block-diagram images from .diag files (similar to graphviz’s DOT files).
____

==== Internal diagram source

[blockdiag, "blockdiag-internal-example-diagram", svg]
----
blockdiag {
   blockdiag -> generates -> "block-diagrams";
   blockdiag -> is -> "very easy!";

   blockdiag [color = "greenyellow"];
   "block-diagrams" [color = "pink"];
   "very easy!" [color = "orange"];
}
----

==== External diagram source file

blockdiag::{imagesdir}/asciidoctor-diagrams_overview/uml/blockdiag_blockdiag.diag[format="svg"]

[[section-nwdiag]]
=== nwdiag

[quote, Takeshi KOMIYA, http://blockdiag.com/en/nwdiag/index.html]
____
_nwdiag_ generates network-diagram images from .diag files (similar to graphviz’s DOT files).
____

==== Internal diagram source

[nwdiag, "nwdiag-internal-example-diagram", svg]
----
nwdiag {
   network dmz {
      address = "210.x.x.x/24"

      web01 [address = "210.x.x.1"];
      web02 [address = "210.x.x.2"];
   }
   network internal {
      address = "172.x.x.x/24";

      web01 [address = "172.x.x.1"];
      db01;
      app01;
   }
}
----

And, `nwdiag` package includes more scripts called `rackdiag` and `packetdiag`.

==== rackdiag

`rackdiag` generates rack-structure diagram images:

[rackdiag, "nwdiag-rackdiag-internal-example-diagram", svg]
----
rackdiag {
   8U;

   1: UPS [2U];
   3: DB Server
   4: Web Server
   5: Web Server
   6: Web Server
   7: Load Balancer
   8: L3 Switch
}
----

==== packetdiag

`packetdiag` generates packet header diagram images:

[packetdiag, "nwdiag-packetdiag-internal-example-diagram", svg]
----
packetdiag {
   0-7: Source Port
   8-15: Destination Port
   16-31: Sequence Number
   32-35: AckNo
   36-39: Offset
   40-47: Reserved
}
----

==== External diagram source file

nwdiag::{imagesdir}/asciidoctor-diagrams_overview/uml/blockdiag_nwdiag.diag[format="svg"]

[[section-seqdiag]]
=== seqdiag

[quote, Takeshi KOMIYA, http://blockdiag.com/en/seqdiag/index.html]
____
_seqdiag_ generates sequence-diagram images from .diag files
(similar to graphviz's DOT files).
____

==== Internal diagram source

[seqdiag, "seqdiag-internal-example-diagram", svg]
----
seqdiag {
   seqdiag -> "sequence-diagrams" [label = "generates"];
   seqdiag --> "is very easy!";
}
----

==== External diagram source file

seqdiag::{imagesdir}/asciidoctor-diagrams_overview/uml/blockdiag_seqdiag.diag[format="svg"]
